export type BadgeTier = "bronze" | "silver" | "gold"
export type BadgeSeries = "curator-of-wonders" | "dimensional-wanderer" | "fellowship-weaver" | "gathering-master" | "stalwart-companion" | "manor-ascendant" | "portal-keeper"

export interface Badge {
  id: string
  name: string
  description: string
  tier: BadgeTier
  series: BadgeSeries
  seriesName: string
  requirement: number
  requirementText: string
  xp: number
  image: string
}

export const BADGE_DEFINITIONS: Badge[] = [
  // Curator of Wonders Series (Collection)
  {
    id: "apprentice-curator",
    name: "Apprentice Curator",
    description: "Begin your journey as a collector",
    tier: "bronze",
    series: "curator-of-wonders",
    seriesName: "Curator of Wonders",
    requirement: 5,
    requirementText: "Add 5 games to your collection",
    xp: 100,
    image: "/badges/collection/apprentice-curator-bronze.png",
  },
  {
    id: "master-curator",
    name: "Master Curator",
    description: "Your collection grows impressive",
    tier: "silver",
    series: "curator-of-wonders",
    seriesName: "Curator of Wonders",
    requirement: 25,
    requirementText: "Add 25 games to your collection",
    xp: 250,
    image: "/badges/collection/master-curator-silver.png",
  },
  {
    id: "grand-curator",
    name: "Grand Curator",
    description: "A legendary collection worthy of the manor",
    tier: "gold",
    series: "curator-of-wonders",
    seriesName: "Curator of Wonders",
    requirement: 100,
    requirementText: "Add 100 games to your collection",
    xp: 500,
    image: "/badges/collection/grand-curator-gold.png",
  },
  // Dimensional Wanderer Series (Category Explorer)
  {
    id: "curious-explorer",
    name: "Curious Explorer",
    description: "Begin exploring different gaming realms",
    tier: "bronze",
    series: "dimensional-wanderer",
    seriesName: "Dimensional Wanderer",
    requirement: 2,
    requirementText: "Own games from 2 different categories",
    xp: 100,
    image: "/badges/category/curious-explorer-bronze.png",
  },
  {
    id: "realm-walker",
    name: "Realm Walker",
    description: "Your travels span multiple dimensions",
    tier: "silver",
    series: "dimensional-wanderer",
    seriesName: "Dimensional Wanderer",
    requirement: 3,
    requirementText: "Own games from 3 different categories",
    xp: 250,
    image: "/badges/category/realm-walker-silver.png",
  },
  {
    id: "dimensional-master",
    name: "Dimensional Master",
    description: "Master of all gaming dimensions",
    tier: "gold",
    series: "dimensional-wanderer",
    seriesName: "Dimensional Wanderer",
    requirement: 4,
    requirementText: "Own games from all 4 categories",
    xp: 500,
    image: "/badges/category/dimensional-master-gold.png",
  },
  // Fellowship Weaver Series (Social)
  {
    id: "bond-forger",
    name: "Bond Forger",
    description: "Begin building your fellowship",
    tier: "bronze",
    series: "fellowship-weaver",
    seriesName: "Fellowship Weaver",
    requirement: 3,
    requirementText: "Connect with 3 friends",
    xp: 100,
    image: "/badges/social/bond-forger-bronze.png",
  },
  {
    id: "circle-builder",
    name: "Circle Builder",
    description: "Your circle of friends grows strong",
    tier: "silver",
    series: "fellowship-weaver",
    seriesName: "Fellowship Weaver",
    requirement: 10,
    requirementText: "Connect with 10 friends",
    xp: 250,
    image: "/badges/social/circle-builder-silver.png",
  },
  {
    id: "fellowship-master",
    name: "Fellowship Master",
    description: "A true master of fellowship and community",
    tier: "gold",
    series: "fellowship-weaver",
    seriesName: "Fellowship Weaver",
    requirement: 25,
    requirementText: "Connect with 25 friends",
    xp: 500,
    image: "/badges/social/fellowship-master-gold.png",
  },
  // Gathering Master Series (Event Hosting)
  {
    id: "first-gathering",
    name: "First Gathering",
    description: "Host your first gaming event",
    tier: "bronze",
    series: "gathering-master",
    seriesName: "Gathering Master",
    requirement: 1,
    requirementText: "Host 1 event",
    xp: 100,
    image: "/badges/events-hosted/first-gathering-bronze.png",
  },
  {
    id: "regular-host",
    name: "Regular Host",
    description: "Become a regular event organizer",
    tier: "silver",
    series: "gathering-master",
    seriesName: "Gathering Master",
    requirement: 5,
    requirementText: "Host 5 events",
    xp: 250,
    image: "/badges/events-hosted/regular-host-silver.png",
  },
  {
    id: "grand-orchestrator",
    name: "Grand Orchestrator",
    description: "Master the art of grand gatherings",
    tier: "gold",
    series: "gathering-master",
    seriesName: "Gathering Master",
    requirement: 20,
    requirementText: "Host 20 events",
    xp: 500,
    image: "/badges/events-hosted/grand-orchestrator-gold.png",
  },
  // Manor Ascendant Series (Level)
  {
    id: "ground-floor-master",
    name: "Ground Floor Master",
    description: "Master the ground floor of the manor",
    tier: "bronze",
    series: "manor-ascendant",
    seriesName: "Manor Ascendant",
    requirement: 5,
    requirementText: "Reach Level 5",
    xp: 100,
    image: "/badges/manor/ground-floor-master-bronze.png",
  },
  {
    id: "second-floor-master",
    name: "Second Floor Master",
    description: "Ascend to the second floor",
    tier: "silver",
    series: "manor-ascendant",
    seriesName: "Manor Ascendant",
    requirement: 10,
    requirementText: "Reach Level 10",
    xp: 250,
    image: "/badges/manor/second-floor-master-silver.png",
  },
  {
    id: "basement-lord",
    name: "Basement Lord",
    description: "Unlock the secrets of the basement",
    tier: "gold",
    series: "manor-ascendant",
    seriesName: "Manor Ascendant",
    requirement: 15,
    requirementText: "Reach Level 15",
    xp: 500,
    image: "/badges/manor/basement-lord-gold.png",
  },
  // Portal Keeper Series (BGG Integration)
  {
    id: "portal-novice",
    name: "Portal Novice",
    description: "Open your first portal to BoardGameGeek",
    tier: "bronze",
    series: "portal-keeper",
    seriesName: "Portal Keeper",
    requirement: 1,
    requirementText: "Import 1 game from BGG",
    xp: 100,
    image: "/badges/bgg/portal-novice-bronze.png",
  },
  {
    id: "portal-adept",
    name: "Portal Adept",
    description: "Harness the power of the BGG portal",
    tier: "silver",
    series: "portal-keeper",
    seriesName: "Portal Keeper",
    requirement: 10,
    requirementText: "Import 10 games from BGG",
    xp: 250,
    image: "/badges/bgg/portal-adept-silver.png",
  },
  {
    id: "portal-master",
    name: "Portal Master",
    description: "Master of dimensional game collection",
    tier: "gold",
    series: "portal-keeper",
    seriesName: "Portal Keeper",
    requirement: 50,
    requirementText: "Import 50 games from BGG",
    xp: 500,
    image: "/badges/bgg/portal-master-gold.png",
  },
  // Stalwart Companion Series (Event Attendance)
  {
    id: "eager-newcomer",
    name: "Eager Newcomer",
    description: "Join your first gaming gatherings",
    tier: "bronze",
    series: "stalwart-companion",
    seriesName: "Stalwart Companion",
    requirement: 3,
    requirementText: "Attend 3 events",
    xp: 100,
    image: "/badges/events-attended/eager-newcomer-bronze.png",
  },
  {
    id: "reliable-ally",
    name: "Reliable Ally",
    description: "Become a dependable companion",
    tier: "silver",
    series: "stalwart-companion",
    seriesName: "Stalwart Companion",
    requirement: 10,
    requirementText: "Attend 10 events",
    xp: 250,
    image: "/badges/events-attended/reliable-ally-silver.png",
  },
  {
    id: "legendary-companion",
    name: "Legendary Companion",
    description: "A legendary presence at every gathering",
    tier: "gold",
    series: "stalwart-companion",
    seriesName: "Stalwart Companion",
    requirement: 25,
    requirementText: "Attend 25 events",
    xp: 500,
    image: "/badges/events-attended/legendary-companion-gold.png",
  },
]

// Helper function to get badges by series
export function getBadgesBySeries(series: BadgeSeries): Badge[] {
  return BADGE_DEFINITIONS.filter((badge) => badge.series === series)
}

// Helper function to get badge by id
export function getBadgeById(id: string): Badge | undefined {
  return BADGE_DEFINITIONS.find((badge) => badge.id === id)
}
