export interface Game {
  id: number
  title: string
  image: string
  rating: number
  playerCount: string
  minPlayers: number
  maxPlayers: number
  playTime: string
  minPlayTime: number
  maxPlayTime: number
  category: string
  mechanics: string[]
  yearPublished: number
  owned: boolean
  wishlist: boolean
}

export const MOCK_GAMES: Game[] = [
  {
    id: 1,
    title: "Wingspan",
    image: "/wingspan-board-game-box.png",
    rating: 4.8,
    playerCount: "1-5",
    minPlayers: 1,
    maxPlayers: 5,
    playTime: "40-70",
    minPlayTime: 40,
    maxPlayTime: 70,
    category: "Strategy",
    mechanics: ["engine-building", "card-drafting"],
    yearPublished: 2019,
    owned: true,
    wishlist: false,
  },
  {
    id: 2,
    title: "Azul",
    image: "/azul-board-game-box.png",
    rating: 4.6,
    playerCount: "2-4",
    minPlayers: 2,
    maxPlayers: 4,
    playTime: "30-45",
    minPlayTime: 30,
    maxPlayTime: 45,
    category: "Abstract",
    mechanics: ["pattern-building", "tile-placement"],
    yearPublished: 2017,
    owned: true,
    wishlist: false,
  },
  {
    id: 3,
    title: "Gloomhaven",
    image: "/gloomhaven-board-game-box.png",
    rating: 4.9,
    playerCount: "1-4",
    minPlayers: 1,
    maxPlayers: 4,
    playTime: "60-120",
    minPlayTime: 60,
    maxPlayTime: 120,
    category: "Thematic",
    mechanics: ["cooperative", "deck-building", "campaign"],
    yearPublished: 2017,
    owned: true,
    wishlist: false,
  },
  {
    id: 4,
    title: "Ticket to Ride",
    image: "/ticket-to-ride-board-game-box.png",
    rating: 4.4,
    playerCount: "2-5",
    minPlayers: 2,
    maxPlayers: 5,
    playTime: "30-60",
    minPlayTime: 30,
    maxPlayTime: 60,
    category: "Family",
    mechanics: ["set-collection", "route-building"],
    yearPublished: 2004,
    owned: false,
    wishlist: true,
  },
  {
    id: 5,
    title: "Scythe",
    image: "/scythe-board-game-box.png",
    rating: 4.7,
    playerCount: "1-5",
    minPlayers: 1,
    maxPlayers: 5,
    playTime: "90-115",
    minPlayTime: 90,
    maxPlayTime: 115,
    category: "Strategy",
    mechanics: ["area-control", "engine-building", "worker-placement"],
    yearPublished: 2016,
    owned: true,
    wishlist: false,
  },
  {
    id: 6,
    title: "Pandemic",
    image: "/pandemic-board-game-box.png",
    rating: 4.5,
    playerCount: "2-4",
    minPlayers: 2,
    maxPlayers: 4,
    playTime: "45-60",
    minPlayTime: 45,
    maxPlayTime: 60,
    category: "Cooperative",
    mechanics: ["cooperative", "hand-management"],
    yearPublished: 2008,
    owned: true,
    wishlist: false,
  },
  {
    id: 7,
    title: "Terraforming Mars",
    image: "/terraforming-mars-board-game.jpg",
    rating: 4.7,
    playerCount: "1-5",
    minPlayers: 1,
    maxPlayers: 5,
    playTime: "120-180",
    minPlayTime: 120,
    maxPlayTime: 180,
    category: "Strategy",
    mechanics: ["engine-building", "card-drafting"],
    yearPublished: 2016,
    owned: true,
    wishlist: false,
  },
  {
    id: 8,
    title: "Catan",
    image: "/catan-board-game.jpg",
    rating: 4.3,
    playerCount: "3-4",
    minPlayers: 3,
    maxPlayers: 4,
    playTime: "60-120",
    minPlayTime: 60,
    maxPlayTime: 120,
    category: "Family",
    mechanics: ["trading", "dice-rolling"],
    yearPublished: 1995,
    owned: true,
    wishlist: false,
  },
]
